In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv("/content/sample_data/Titanic-Dataset.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
df.drop(columns=["PassengerId","Name","Ticket"],axis=1,inplace=True)

In [ ]:
df.head()

Survived  Pclass  Gender   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Gender    891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Cabin     204 non-null    object 
 8   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB


In [ ]:
df['Cabin'].value_counts()

B96 B98        4
G6             4
C23 C25 C27    4
C22 C26        3
F33            3
              ..
E34            1
C7             1
C54            1
E36            1
C148           1
Name: Cabin, Length: 147, dtype: int64

In [ ]:
df.drop(columns=["Cabin"],axis=1,inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Gender    891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [ ]:
df = df[df["Age"].notnull()].copy()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  714 non-null    int64  
 1   Pclass    714 non-null    int64  
 2   Gender    714 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     714 non-null    int64  
 5   Parch     714 non-null    int64  
 6   Fare      714 non-null    float64
 7   Embarked  712 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 50.2+ KB


In [ ]:
df = df[df["Embarked"].notnull()].copy()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  712 non-null    int64  
 1   Pclass    712 non-null    int64  
 2   Gender    712 non-null    object 
 3   Age       712 non-null    float64
 4   SibSp     712 non-null    int64  
 5   Parch     712 non-null    int64  
 6   Fare      712 non-null    float64
 7   Embarked  712 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 50.1+ KB


In [ ]:
X = df.drop(columns=["Survived"],axis=1)
y = df["Survived"]

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    712 non-null    int64  
 1   Gender    712 non-null    object 
 2   Age       712 non-null    float64
 3   SibSp     712 non-null    int64  
 4   Parch     712 non-null    int64  
 5   Fare      712 non-null    float64
 6   Embarked  712 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 44.5+ KB


In [ ]:
y[:5]

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [ ]:
X.shape, y.shape

((712, 7), (712,))

In [ ]:
X_category_df = X[['Pclass','Gender','Embarked']]
X_remaining_df = X[['Age','SibSp','Parch','Fare']]
X_category_df.shape, X_remaining_df.shape

((712, 3), (712, 4))

In [ ]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
X_category_df_le = X_category_df.apply(le.fit_transform)
X_category_df_le.head()

Pclass  Gender  Embarked
0       2       1         2
1       0       0         0
2       2       0         2
3       0       0         2
4       2       1         2

In [ ]:
X_after_le = pd.concat([X_category_df_le,X_remaining_df],axis=1,ignore_index=False)
X_after_le.head()

Pclass  Gender  Embarked   Age  SibSp  Parch     Fare
0       2       1         2  22.0      1      0   7.2500
1       0       0         0  38.0      1      0  71.2833
2       2       0         2  26.0      0      0   7.9250
3       0       0         2  35.0      1      0  53.1000
4       2       1         2  35.0      0      0   8.0500

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_after_le, y, test_size=0.25, stratify = y)

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((534, 7), (178, 7), (534,), (178,))

In [ ]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 534 entries, 104 to 722
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    534 non-null    int64  
 1   Gender    534 non-null    int64  
 2   Embarked  534 non-null    int64  
 3   Age       534 non-null    float64
 4   SibSp     534 non-null    int64  
 5   Parch     534 non-null    int64  
 6   Fare      534 non-null    float64
dtypes: float64(2), int64(5)
memory usage: 33.4 KB


In [ ]:
X_train['Pclass'].value_counts()

2    270
1    135
0    129
Name: Pclass, dtype: int64

In [ ]:
X_train['Pclass'][:5]

104    2
72     1
385    1
328    2
366    0
Name: Pclass, dtype: int64

In [ ]:
X_train['Embarked'].value_counts()

2    426
0     92
1     16
Name: Embarked, dtype: int64

In [ ]:
numerical_df_X_train = X_train[['Age','SibSp','Parch','Fare']]
numerical_df_X_train.head()


Age  SibSp  Parch    Fare
104  37.0      2      0   7.925
72   21.0      0      0  73.500
385  18.0      0      0  73.500
328  31.0      1      1  20.525
366  60.0      1      0  75.250

In [ ]:
numerical_df_X_test = X_test[['Age','SibSp','Parch','Fare']]
numerical_df_X_test.head()

Age  SibSp  Parch     Fare
273  37.0      0      1  29.7000
627  21.0      0      0  77.9583
363  35.0      0      0   7.0500
853  16.0      0      1  39.4000
207  26.0      0      0  18.7875

In [ ]:
# Categoric features are: Embarked, Pclass, Gender
# Numreical features are: Age,SibSp,Parch,Fare

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(numerical_df_X_train) # This function is used to learning the data
X_tr_numeric = scaler.transform(numerical_df_X_train) # This function is used convert the data into learnt format

In [ ]:
X_tst_numeric = scaler.transform(numerical_df_X_test)
X_tst_numeric.shape

(178, 4)

In [ ]:
X_tst_numeric[:5]

array([[ 0.52486397, -0.57434642,  0.61922874, -0.07261001],
       [-0.57777625, -0.57434642, -0.50549285,  0.93710595],
       [ 0.38703394, -0.57434642, -0.50549285, -0.54651951],
       [-0.92235132, -0.57434642,  0.61922874,  0.1303446 ],
       [-0.23320118, -0.57434642, -0.50549285, -0.30093396]])

In [ ]:
X_tr_numeric.shape

(534, 4)

In [ ]:
X_tr_numeric[:5]

array([[ 0.52486397,  1.50498232, -0.50549285, -0.52821175],
       [-0.57777625, -0.57434642, -0.50549285,  0.84382424],
       [-0.78452129, -0.57434642, -0.50549285,  0.84382424],
       [ 0.11137389,  0.46531795,  0.61922874, -0.26457997],
       [ 2.10990928,  0.46531795, -0.50549285,  0.88043976]])

In [ ]:
category_df_X_train = X_train[['Pclass','Gender','Embarked']]
category_df_X_train.head()

Pclass  Gender  Embarked
104       2       1         2
72        1       1         2
385       1       1         2
328       2       0         2
366       0       0         0

In [ ]:
category_df_X_test = X_test[['Pclass','Gender','Embarked']]
category_df_X_test.head()

Pclass  Gender  Embarked
273       0       1         0
627       0       0         2
363       2       1         2
853       0       0         2
207       2       1         0

In [ ]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown='ignore')
enc.fit(category_df_X_train)
X_train_cat_ohe = enc.transform(category_df_X_train)
X_test_cat_ohe = enc.transform(category_df_X_test)

In [ ]:
X_train_cat_ohe.shape,X_test_cat_ohe.shape

((534, 8), (178, 8))

In [ ]:
type(X_train_cat_ohe.toarray())

numpy.ndarray

In [ ]:
X_train_cat_ohe.toarray()[:5]

array([[0., 0., 1., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 1., 0., 0.]])

In [ ]:
X_test_cat_ohe.toarray()[:5]

array([[1., 0., 0., 0., 1., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1., 1., 0., 0.]])

In [ ]:
X_train_df = pd.concat([pd.DataFrame(X_train_cat_ohe.toarray()),pd.DataFrame(X_tr_numeric)],axis=1,ignore_index=True)
X_test_df = pd.concat([pd.DataFrame(X_test_cat_ohe.toarray()),pd.DataFrame(X_tst_numeric)],axis=1,ignore_index=True)

In [ ]:
X_train_df.shape, X_test_df.shape

((534, 12), (178, 12))

In [ ]:
X_train_df.rename(columns={0:'Pclass_1',1:'Pclass_2',2:'Pclass_3',3:'Gender_1',4:'Gender_2',5:'Embarked_1',6:'Embarked_2',7:'Embarked_3',8:'Age',9:'SibSp',10:'Parch',11:'Fare'},inplace=True)

In [ ]:
X_test_df.rename(columns={0:'Pclass_1',1:'Pclass_2',2:'Pclass_3',3:'Gender_1',4:'Gender_2',5:'Embarked_1',6:'Embarked_2',7:'Embarked_3',8:'Age',9:'SibSp',10:'Parch',11:'Fare'},inplace=True)

In [ ]:
X_train_df.head()

Pclass_1  Pclass_2  Pclass_3  Gender_1  Gender_2  Embarked_1  Embarked_2  \
0       0.0       0.0       1.0       0.0       1.0         0.0         0.0   
1       0.0       1.0       0.0       0.0       1.0         0.0         0.0   
2       0.0       1.0       0.0       0.0       1.0         0.0         0.0   
3       0.0       0.0       1.0       1.0       0.0         0.0         0.0   
4       1.0       0.0       0.0       1.0       0.0         1.0         0.0   

   Embarked_3       Age     SibSp     Parch      Fare  
0         1.0  0.524864  1.504982 -0.505493 -0.528212  
1         1.0 -0.577776 -0.574346 -0.505493  0.843824  
2         1.0 -0.784521 -0.574346 -0.505493  0.843824  
3         1.0  0.111374  0.465318  0.619229 -0.264580  
4         0.0  2.109909  0.465318 -0.505493  0.880440

In [ ]:
X_test_df.head()

Pclass_1  Pclass_2  Pclass_3  Gender_1  Gender_2  Embarked_1  Embarked_2  \
0       1.0       0.0       0.0       0.0       1.0         1.0         0.0   
1       1.0       0.0       0.0       1.0       0.0         0.0         0.0   
2       0.0       0.0       1.0       0.0       1.0         0.0         0.0   
3       1.0       0.0       0.0       1.0       0.0         0.0         0.0   
4       0.0       0.0       1.0       0.0       1.0         1.0         0.0   

   Embarked_3       Age     SibSp     Parch      Fare  
0         0.0  0.524864 -0.574346  0.619229 -0.072610  
1         1.0 -0.577776 -0.574346 -0.505493  0.937106  
2         1.0  0.387034 -0.574346 -0.505493 -0.546520  
3         1.0 -0.922351 -0.574346  0.619229  0.130345  
4         0.0 -0.233201 -0.574346 -0.505493 -0.300934

In [ ]:
col_lst = X_train_df.columns

In [ ]:
print(col_lst)

Index(['Pclass_1', 'Pclass_2', 'Pclass_3', 'Gender_1', 'Gender_2',
       'Embarked_1', 'Embarked_2', 'Embarked_3', 'Age', 'SibSp', 'Parch',
       'Fare'],
      dtype='object')


In [ ]:
""" EDA Techniques:
1. Histogram
2. Distribution Plots
3. Box Plots
4. Scatter Plots
5. KDE Plots
6. Correlation Matrix

# Statistical Modelling

1. Hypothesis testing
2. KS Test"""

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(np.array(X_train_df),np.array(y_train))

KNeighborsClassifier(n_neighbors=3)

In [ ]:
y_predict_values = neigh.predict(np.array(X_test_df))

In [ ]:
y_predict_values[:5]

array([0, 0, 0, 0, 0])

In [ ]:
y_test[:5]

499    0
796    1
733    0
30     0
787    0
Name: Survived, dtype: int64

In [ ]:
from sklearn.metrics import classification_report


print(classification_report(np.array(y_test), y_predict_values, target_names=['Dead','Alive']))

              precision    recall  f1-score   support

        Dead       0.82      0.81      0.82       106
       Alive       0.73      0.74      0.73        72

    accuracy                           0.78       178
   macro avg       0.77      0.77      0.77       178
weighted avg       0.78      0.78      0.78       178



In [ ]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(np.array(y_test), y_predict_values))

[[86 20]
 [19 53]]


In [ ]:
X_tr, X_cv, y_tr, y_cv = train_test_split(X_train_df, y_train, test_size=0.15, stratify = y_train)
X_tr.shape, X_cv.shape, y_tr.shape, y_cv.shape

((453, 12), (81, 12), (453,), (81,))

In [ ]:
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(np.array(X_tr),np.array(y_tr))

KNeighborsClassifier(n_neighbors=3)

In [ ]:
y_predict_values = neigh.predict(np.array(X_cv))
print(classification_report(np.array(y_cv), y_predict_values, target_names=['Dead','Alive']))

              precision    recall  f1-score   support

        Dead       0.78      0.81      0.80        48
       Alive       0.71      0.67      0.69        33

    accuracy                           0.75        81
   macro avg       0.74      0.74      0.74        81
weighted avg       0.75      0.75      0.75        81



In [ ]:
y_predict_values = neigh.predict(np.array(X_test_df))
print(classification_report(np.array(y_test), y_predict_values, target_names=['Dead','Alive']))

              precision    recall  f1-score   support

        Dead       0.82      0.79      0.80       106
       Alive       0.71      0.74      0.72        72

    accuracy                           0.77       178
   macro avg       0.76      0.76      0.76       178
weighted avg       0.77      0.77      0.77       178



In [ ]:
from sklearn.model_selection import GridSearchCV

params = {'n_neighbors':[1,2,3,4,5,6,7,8,9,10]}

neigh = KNeighborsClassifier()
clf_cv = GridSearchCV(neigh, params,cv=10,return_train_score=True,scoring='accuracy')
clf_cv.fit(np.array(X_tr),np.array(y_tr))
print(clf_cv.best_params_)

{'n_neighbors': 10}


In [ ]:
neigh = KNeighborsClassifier(n_neighbors=10)
neigh.fit(np.array(X_tr),np.array(y_tr))

KNeighborsClassifier(n_neighbors=10)

In [ ]:
y_predict_values = neigh.predict(np.array(X_cv))
print(classification_report(np.array(y_cv), y_predict_values, target_names=['Dead','Alive']))

              precision    recall  f1-score   support

        Dead       0.81      1.00      0.90        48
       Alive       1.00      0.67      0.80        33

    accuracy                           0.86        81
   macro avg       0.91      0.83      0.85        81
weighted avg       0.89      0.86      0.86        81

