In [ ]:
# Numpy module - Numerical Python - - is used for working with arrays 
# It also has functions for working in domain of linear algebra, fourier transform, and matrices
# NumPy aims to provide an array object that is up to 50x faster than traditional Python lists
# NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.(locality of reference)
# it is optimized to work with latest CPU architectures
# NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++

In [ ]:
# Creating numpy arays, checking version, type()
# 0d, 1d,2d,3d,4d.... arrays
# Checking the dimensions, ndim, ndmin

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [26]:
import numpy as np

a = np.array(42) # 0 dimensional array
a

array(42)

In [34]:
a.shape

()

In [27]:
b = np.array([1, 2, 3, 4, 5]) # 1d array
b

array([1, 2, 3, 4, 5])

In [31]:
b.shape

(5,)

In [37]:
len(b)

5

In [28]:
c = np.array([[1, 2, 3], [4, 5, 6]]) # 2d array
c

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
c.shape

(2, 3)

In [36]:
len(c)

2

In [29]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) # 3d array
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [30]:
d.ndim # number of dimensions

3

In [33]:
d.shape

(2, 2, 3)

In [35]:
len(d)

2

In [40]:
# how to ceate various types of arrays

a= np.arange(50)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [41]:
a.ndim

1

In [43]:
a= np.arange(2,50,10)
a

array([ 2, 12, 22, 32, 42])

In [44]:
a= np.linspace(2,50,10)
a

array([ 2.        ,  7.33333333, 12.66666667, 18.        , 23.33333333,
       28.66666667, 34.        , 39.33333333, 44.66666667, 50.        ])

In [45]:
a= np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
a= np.zeros((10,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
a= np.eye(7,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [61]:
np.random.rand(4) # uniform distributon numbers

array([0.03859623, 0.18663685, 0.61088484, 0.91266084])

In [65]:
u = np.random.randn(4) # normal distributon numbers
u

array([-0.7108388 ,  1.23416586,  0.39876462, -0.8882961 ])

In [66]:
u.dtype

dtype('float64')