In [2]:
import numpy as np

a = np.arange(10, dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [4]:
a= np.array([1+2j,2+4j,3+5j,4+6j])
a.dtype

dtype('complex128')

In [5]:
a

array([1.+2.j, 2.+4.j, 3.+5.j, 4.+6.j])

In [6]:
a= np.array([True,False,True,False,True,False])
a

array([ True, False,  True, False,  True, False])

In [7]:
a= np.array(['Ram','Robert','Rahim'])
a

array(['Ram', 'Robert', 'Rahim'], dtype='<U6')

In [8]:
# indexing and slicing

a= np.arange(10)
a[2]

2

In [9]:
a= np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [10]:
a[2][2]

3

In [13]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a[1:8:2]

array([1, 3, 5, 7])

In [14]:
a[0:9:3]

array([0, 3, 6])

In [15]:
a[5:]

array([5, 6, 7, 8, 9])

In [16]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [17]:
b= np.arange(5)
b

array([0, 1, 2, 3, 4])

In [19]:
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [24]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
c= a[::2].copy() # Copy
c

array([0, 2, 4, 6, 8])

In [26]:
np.shares_memory(a,c)

False

In [27]:
a[2] = 5
a[6] = 7
a

array([0, 1, 5, 3, 4, 5, 7, 7, 8, 9])

In [28]:
c

array([0, 2, 4, 6, 8])

In [29]:
a= np.random.randint(0,20,15)
a

array([ 6,  8, 15,  7,  9, 13,  0, 10,  2, 11,  8, 19, 16,  3, 14])

In [30]:
mask = (a%2==0)
extract_from_a = a[mask]
extract_from_a

array([ 6,  8,  0, 10,  2,  8, 16, 14])

In [31]:
a[mask] = -1
a

array([-1, -1, 15,  7,  9, 13, -1, -1, -1, 11, -1, 19, -1,  3, -1])

In [32]:
a+1

array([ 0,  0, 16,  8, 10, 14,  0,  0,  0, 12,  0, 20,  0,  4,  0])

In [33]:
a*2

array([-2, -2, 30, 14, 18, 26, -2, -2, -2, 22, -2, 38, -2,  6, -2])

In [34]:
a**2

array([  1,   1, 225,  49,  81, 169,   1,   1,   1, 121,   1, 361,   1,
         9,   1], dtype=int32)

In [35]:
a*a

array([  1,   1, 225,  49,  81, 169,   1,   1,   1, 121,   1, 361,   1,
         9,   1])

In [ ]:
a= np.array([1,2,3,4])
b= np.array([5,2,2,4])

In [36]:
a==b

C:\Users\PRASAD\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

ValueError: operands could not be broadcast together with shapes (15,) (5,) 

In [38]:
a.T

array([-1, -1, 15,  7,  9, 13, -1, -1, -1, 11, -1, 19, -1,  3, -1])

In [42]:
a= np.array([[1,2,3,4],[5,4,5,3]])
a

array([[1, 2, 3, 4],
       [5, 4, 5, 3]])

In [43]:
a.ndim

2

In [44]:
a.T

array([[1, 5],
       [2, 4],
       [3, 5],
       [4, 3]])

In [45]:
np.sum(a)

27