In [ ]:
np.ravel() # To flatten the arrays
np.reshape() # Gives a new shape to an array without changing its data - returns View
np.resize() # Return a new array with the specified shape - returns Copy
np.sort() # Retuns a sorted copy
np.concatenate()
np.stack()
np.vstack()
np.hstack()
np.array_split(arr, 3)
np.hsplit()

In [80]:
import numpy as np

a= np.random.randint(0,20,30)
a

array([18,  7, 10,  0,  6, 16,  2, 17, 13, 19,  9, 12,  8, 14,  6, 13,  9,
       18,  7,  3,  3,  8,  8, 12, 19, 17, 13,  8,  0, 18])

In [81]:
a.shape

(30,)

In [82]:
b= a.reshape((5,6))
b

array([[18,  7, 10,  0,  6, 16],
       [ 2, 17, 13, 19,  9, 12],
       [ 8, 14,  6, 13,  9, 18],
       [ 7,  3,  3,  8,  8, 12],
       [19, 17, 13,  8,  0, 18]])

In [83]:
a[10] = 100000
a

array([    18,      7,     10,      0,      6,     16,      2,     17,
           13,     19, 100000,     12,      8,     14,      6,     13,
            9,     18,      7,      3,      3,      8,      8,     12,
           19,     17,     13,      8,      0,     18])

In [84]:
a.shape

(30,)

In [85]:
b

array([[    18,      7,     10,      0,      6,     16],
       [     2,     17,     13,     19, 100000,     12],
       [     8,     14,      6,     13,      9,     18],
       [     7,      3,      3,      8,      8,     12],
       [    19,     17,     13,      8,      0,     18]])

In [89]:
c= np.resize(a,(5,6))
c

array([[    18,      7,     10,      0,      6,     16],
       [     2,     17,     13,     19, 100000,     12],
       [     8,     14,      6,     13,      9,     18],
       [     7,      3,      3,      8,      8,     12],
       [    19,     17,     13,      8,      0,     18]])

In [90]:
a[10] = 200000


IndexError: index 10 is out of bounds for axis 0 with size 5

In [91]:
a.shape

(5, 6)

In [92]:
u = np.random.randint(0,20,20)
u

array([10,  0, 19,  7,  7,  7, 11,  2,  2,  3,  0,  3, 12,  8,  0,  5, 12,
        9, 13, 16])

In [93]:
u.shape

(20,)

In [94]:
v= np.resize(u,(5,4))
v

array([[10,  0, 19,  7],
       [ 7,  7, 11,  2],
       [ 2,  3,  0,  3],
       [12,  8,  0,  5],
       [12,  9, 13, 16]])

In [95]:
u[8] = 200000
u

array([    10,      0,     19,      7,      7,      7,     11,      2,
       200000,      3,      0,      3,     12,      8,      0,      5,
           12,      9,     13,     16])

In [96]:
v

array([[10,  0, 19,  7],
       [ 7,  7, 11,  2],
       [ 2,  3,  0,  3],
       [12,  8,  0,  5],
       [12,  9, 13, 16]])

In [97]:
v.shape

(5, 4)

In [98]:
v.ravel()

array([10,  0, 19,  7,  7,  7, 11,  2,  2,  3,  0,  3, 12,  8,  0,  5, 12,
        9, 13, 16])

In [99]:
v.ravel().shape

(20,)

In [100]:
v

array([[10,  0, 19,  7],
       [ 7,  7, 11,  2],
       [ 2,  3,  0,  3],
       [12,  8,  0,  5],
       [12,  9, 13, 16]])

In [101]:
v.sort()

In [102]:
v

array([[ 0,  7, 10, 19],
       [ 2,  7,  7, 11],
       [ 0,  2,  3,  3],
       [ 0,  5,  8, 12],
       [ 9, 12, 13, 16]])

In [103]:
v

array([[ 0,  7, 10, 19],
       [ 2,  7,  7, 11],
       [ 0,  2,  3,  3],
       [ 0,  5,  8, 12],
       [ 9, 12, 13, 16]])

In [106]:
v.shape

(5, 4)

In [104]:
w= np.concatenate((v,v))
w

array([[ 0,  7, 10, 19],
       [ 2,  7,  7, 11],
       [ 0,  2,  3,  3],
       [ 0,  5,  8, 12],
       [ 9, 12, 13, 16],
       [ 0,  7, 10, 19],
       [ 2,  7,  7, 11],
       [ 0,  2,  3,  3],
       [ 0,  5,  8, 12],
       [ 9, 12, 13, 16]])

In [105]:
w.shape

(10, 4)

In [107]:
x = np.vstack((v,v))
x

array([[ 0,  7, 10, 19],
       [ 2,  7,  7, 11],
       [ 0,  2,  3,  3],
       [ 0,  5,  8, 12],
       [ 9, 12, 13, 16],
       [ 0,  7, 10, 19],
       [ 2,  7,  7, 11],
       [ 0,  2,  3,  3],
       [ 0,  5,  8, 12],
       [ 9, 12, 13, 16]])

In [108]:
x.shape

(10, 4)

In [109]:
y= np.hstack((v,v))
y

array([[ 0,  7, 10, 19,  0,  7, 10, 19],
       [ 2,  7,  7, 11,  2,  7,  7, 11],
       [ 0,  2,  3,  3,  0,  2,  3,  3],
       [ 0,  5,  8, 12,  0,  5,  8, 12],
       [ 9, 12, 13, 16,  9, 12, 13, 16]])

In [110]:
y.shape

(5, 8)

In [111]:
z = np.stack((v,v))
z

array([[[ 0,  7, 10, 19],
        [ 2,  7,  7, 11],
        [ 0,  2,  3,  3],
        [ 0,  5,  8, 12],
        [ 9, 12, 13, 16]],

       [[ 0,  7, 10, 19],
        [ 2,  7,  7, 11],
        [ 0,  2,  3,  3],
        [ 0,  5,  8, 12],
        [ 9, 12, 13, 16]]])

In [112]:
z.shape

(2, 5, 4)

In [113]:
p = np.random.randint(1,30,15)
p

array([17, 23,  3,  3, 20, 23, 11, 29,  4, 17, 29,  3, 12, 18,  9])

In [116]:
q= np.array_split(p,10)
q

[array([17, 23]),
 array([3, 3]),
 array([20, 23]),
 array([11, 29]),
 array([ 4, 17]),
 array([29]),
 array([3]),
 array([12]),
 array([18]),
 array([9])]

In [119]:
n = p.reshape((3,5))
n

array([[17, 23,  3,  3, 20],
       [23, 11, 29,  4, 17],
       [29,  3, 12, 18,  9]])

In [120]:
n.shape

(3, 5)

In [124]:
s = np.vsplit(n,3)
s

[array([[17, 23,  3,  3, 20]]),
 array([[23, 11, 29,  4, 17]]),
 array([[29,  3, 12, 18,  9]])]